"""Initial

Revision ID: 19c56c94152b
Revises:
Create Date: 2024-12-11 21:49:14.408714

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "19c56c94152b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_policy(
        table_name="items",
        policy_name="items_equal_to_accountid_policy_select_policy_0",
        cmd="SELECT",
        definition="PERMISSIVE",
        expr="owner_id = CAST(coalesce(current_setting('rls.account_id'), '') AS INTEGER)",
    )  # type: ignore
    op.create_policy(
        table_name="items",
        policy_name="items_equal_to_accountid_policy_update_policy_0",
        cmd="UPDATE",
        definition="PERMISSIVE",
        expr="owner_id = CAST(coalesce(current_setting('rls.account_id'), '') AS INTEGER)",
    )  # type: ignore
    op.create_policy(
        table_name="items",
        policy_name="items_greater_than_accountid_policy_select_policy_1",
        cmd="SELECT",
        definition="PERMISSIVE",
        expr="owner_id > CAST(coalesce(current_setting('rls.account_id'), '') AS INTEGER)",
    )  # type: ignore
    op.create_policy(
        table_name="items",
        policy_name="items_smaller_than_or_equal_accountid_policy_all_policy_2",
        cmd="ALL",
        definition="PERMISSIVE",
        expr="owner_id < CAST(coalesce(current_setting('rls.account_id'), '') AS INTEGER)",
    )  # type: ignore
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_policy(
        table_name="items",
        policy_name="items_smaller_than_or_equal_accountid_policy_all_policy_2",
        cmd="ALL",
        definition="PERMISSIVE",
        expr="owner_id < CAST(coalesce(current_setting('rls.account_id'), '') AS INTEGER)",
    )  # type: ignore
    op.drop_policy(
        table_name="items",
        policy_name="items_greater_than_accountid_policy_select_policy_1",
        cmd="SELECT",
        definition="PERMISSIVE",
        expr="owner_id > CAST(coalesce(current_setting('rls.account_id'), '') AS INTEGER)",
    )  # type: ignore
    op.drop_policy(
        table_name="items",
        policy_name="items_equal_to_accountid_policy_update_policy_0",
        cmd="UPDATE",
        definition="PERMISSIVE",
        expr="owner_id = CAST(coalesce(current_setting('rls.account_id'), '') AS INTEGER)",
    )  # type: ignore
    op.drop_policy(
        table_name="items",
        policy_name="items_equal_to_accountid_policy_select_policy_0",
        cmd="SELECT",
        definition="PERMISSIVE",
        expr="owner_id = CAST(coalesce(current_setting('rls.account_id'), '') AS INTEGER)",
    )  # type: ignore
    # ### end Alembic commands ###
