"""add users table equal to account Id restrictive policy for select and update

Revision ID: 5a3640bfc31a
Revises: 75b261ce4397
Create Date: 2024-12-12 23:45:01.407446

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "5a3640bfc31a"
down_revision: Union[str, None] = "75b261ce4397"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.enable_rls("users")  # type: ignore
    op.create_policy(
        table_name="users",
        policy_name="users_equal_to_accountid_policy_select_policy_0",
        cmd="SELECT",
        definition="RESTRICTIVE",
        expr="id = CAST(coalesce(current_setting('rls.account_id'), '') AS INTEGER)",
    )  # type: ignore
    op.create_policy(
        table_name="users",
        policy_name="users_equal_to_accountid_policy_update_policy_0",
        cmd="UPDATE",
        definition="RESTRICTIVE",
        expr="id = CAST(coalesce(current_setting('rls.account_id'), '') AS INTEGER)",
    )  # type: ignore
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_policy(
        table_name="users",
        policy_name="users_equal_to_accountid_policy_update_policy_0",
        cmd="UPDATE",
        definition="RESTRICTIVE",
        expr="id = CAST(coalesce(current_setting('rls.account_id'), '') AS INTEGER)",
    )  # type: ignore
    op.drop_policy(
        table_name="users",
        policy_name="users_equal_to_accountid_policy_select_policy_0",
        cmd="SELECT",
        definition="RESTRICTIVE",
        expr="id = CAST(coalesce(current_setting('rls.account_id'), '') AS INTEGER)",
    )  # type: ignore
    op.disable_rls("users")  # type: ignore
    # ### end Alembic commands ###
