"""test custom operation

Revision ID: 75561a88aaf0
Revises: c3da625851bb
Create Date: 2024-12-16 22:34:06.829813

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "75561a88aaf0"
down_revision: Union[str, None] = "c3da625851bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
