"""change user table policies permissive

Revision ID: 75827d09d6c3
Revises: 5a3640bfc31a
Create Date: 2024-12-13 00:26:51.358111

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "75827d09d6c3"
down_revision: Union[str, None] = "5a3640bfc31a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_policy(
        table_name="users",
        policy_name="users_equal_to_accountid_policy_select_policy_0",
        cmd="SELECT",
        definition="RESTRICTIVE",
        expr="((id = (COALESCE(current_setting('rls.account_id'::text), ''::text))::integer) OR ((NULLIF(current_setting('rls.bypass_rls'::text, true), ''::text))::boolean = true))",
    )  # type: ignore
    op.create_policy(
        table_name="users",
        policy_name="users_equal_to_accountid_policy_select_policy_0",
        cmd="SELECT",
        definition="PERMISSIVE",
        expr="id = CAST(coalesce(current_setting('rls.account_id'), '') AS INTEGER)",
    )  # type: ignore
    op.drop_policy(
        table_name="users",
        policy_name="users_equal_to_accountid_policy_update_policy_0",
        cmd="UPDATE",
        definition="RESTRICTIVE",
        expr="((id = (COALESCE(current_setting('rls.account_id'::text), ''::text))::integer) OR ((NULLIF(current_setting('rls.bypass_rls'::text, true), ''::text))::boolean = true))",
    )  # type: ignore
    op.create_policy(
        table_name="users",
        policy_name="users_equal_to_accountid_policy_update_policy_0",
        cmd="UPDATE",
        definition="PERMISSIVE",
        expr="id = CAST(coalesce(current_setting('rls.account_id'), '') AS INTEGER)",
    )  # type: ignore
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_policy(
        table_name="users",
        policy_name="users_equal_to_accountid_policy_update_policy_0",
        cmd="UPDATE",
        definition="PERMISSIVE",
        expr="id = CAST(coalesce(current_setting('rls.account_id'), '') AS INTEGER)",
    )  # type: ignore
    op.create_policy(
        table_name="users",
        policy_name="users_equal_to_accountid_policy_update_policy_0",
        cmd="UPDATE",
        definition="RESTRICTIVE",
        expr="((id = (COALESCE(current_setting('rls.account_id'::text), ''::text))::integer) OR ((NULLIF(current_setting('rls.bypass_rls'::text, true), ''::text))::boolean = true))",
    )  # type: ignore
    op.drop_policy(
        table_name="users",
        policy_name="users_equal_to_accountid_policy_select_policy_0",
        cmd="SELECT",
        definition="PERMISSIVE",
        expr="id = CAST(coalesce(current_setting('rls.account_id'), '') AS INTEGER)",
    )  # type: ignore
    op.create_policy(
        table_name="users",
        policy_name="users_equal_to_accountid_policy_select_policy_0",
        cmd="SELECT",
        definition="RESTRICTIVE",
        expr="((id = (COALESCE(current_setting('rls.account_id'::text), ''::text))::integer) OR ((NULLIF(current_setting('rls.bypass_rls'::text, true), ''::text))::boolean = true))",
    )  # type: ignore
    # ### end Alembic commands ###
