"""add smaller than or equal instead of smaller than

Revision ID: 75b261ce4397
Revises: 19c56c94152b
Create Date: 2024-12-11 21:59:43.194995

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "75b261ce4397"
down_revision: Union[str, None] = "19c56c94152b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_policy(
        table_name="items",
        policy_name="items_smaller_than_or_equal_accountid_policy_all_policy_2",
        cmd="ALL",
        definition="PERMISSIVE",
        expr="((owner_id < (COALESCE(current_setting('rls.account_id'::text), ''::text))::integer) OR ((NULLIF(current_setting('rls.bypass_rls'::text, true), ''::text))::boolean = true))",
    )  # type: ignore
    op.create_policy(
        table_name="items",
        policy_name="items_smaller_than_or_equal_accountid_policy_all_policy_2",
        cmd="ALL",
        definition="PERMISSIVE",
        expr="owner_id <= CAST(coalesce(current_setting('rls.account_id'), '') AS INTEGER)",
    )  # type: ignore
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_policy(
        table_name="items",
        policy_name="items_smaller_than_or_equal_accountid_policy_all_policy_2",
        cmd="ALL",
        definition="PERMISSIVE",
        expr="owner_id <= CAST(coalesce(current_setting('rls.account_id'), '') AS INTEGER)",
    )  # type: ignore
    op.create_policy(
        table_name="items",
        policy_name="items_smaller_than_or_equal_accountid_policy_all_policy_2",
        cmd="ALL",
        definition="PERMISSIVE",
        expr="((owner_id < (COALESCE(current_setting('rls.account_id'::text), ''::text))::integer) OR ((NULLIF(current_setting('rls.bypass_rls'::text, true), ''::text))::boolean = true))",
    )  # type: ignore
    # ### end Alembic commands ###
