"""Initial

Revision ID: fd7f5bb078af
Revises:
Create Date: 2024-11-24 21:19:26.401327

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "fd7f5bb078af"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_policy(
        table_name="items",
        policy_name="items_permissive_all_policy_0",
        cmd="ALL",
        definition="PERMISSIVE",
        expr="owner_id > CAST(coalesce(current_setting('rls.account_id'), NULL) AS INTEGER)",
    )  # type: ignore
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_policy(tablename="items", policyname="items_permissive_all_policy_0")  # type: ignore
    # ### end Alembic commands ###
